### ISSUE TITLE
iptables should probably use state instead of conntrack

### ISSUE THREAD

**Issue by eric93** [berke1337/firewallmy.systems#7]
See this link:

http://serverfault.com/questions/358996/iptables-whats-the-difference-between-m-state-and-m-conntrack

We don't need anything fancy, so there's no reason to use conntrack.

**Comment by jethrogb** [comment]
There's really no difference between the two.

**Comment by mavam** [comment]
It doesn't hurt to use `state` though if we don't use the advanced `conntrack` features. Although there's not practical difference between the two, I agree with @eric93 that using a `state` here simply adheres to a more prudent design principle: why use more if you can get a way with less.

**Comment by eric93** [comment]
I'm mostly concerned about legacy support for conntrack.

**Comment by justjake** [comment]
Please just submit PRs and discuss there for these one-line diff requests
